### ISSUE TITLE
Can i cite you dataset?

### ISSUE THREAD

**Issue by absingh22** [developmentseed/servir-training-notebooks#5]
I am currently working on comparing different spectral indices in my thesis using your "servir_croptype_workshop_data" data. I was wondering if you could share the citation for the dataset if you have a link.

Thank you for your time and consideration. I greatly appreciate your work.

Sincerely,
Abhishek Singh

**Comment by clotilda-0** [comment]
Requesting you to send me paper link please. @batpad @oliverroick @vgeorge @geohacker  @absingh22
